version: '3.7'
services:
    jenkins:
        build: .
        image: jenkins:lts
        container_name: jenkins
        hostname: jenkins
        network_mode: "bridge"
        restart: always
        ports: 
            - 8080:8080
            - 50000:50000
        volumes: 
          - /home/jenkins:/var/jenkins_home
